{
    "name": "Badge Widget",
    "summary": "Badge widget like on Odoo 14.0",
    "version": "13.0.1.0.0",
    "author": "Terrabit, Dorin Hongu",
    "website": "https://www.terrabit.ro",
    "license": "AGPL-3",
    "category": "Generic Modules",
    "depends": ["web"],
    "data": ["views/assets.xml"],
    "installable": True,
    "qweb": ["static/src/xml/*.xml"],
    "development_status": "Mature",
    "maintainers": ["dhongu"],
    'auto_install': True,
}
