{
    'name': 'Product Configurator Sale',
    'version': '13.0.1.0.0',
    'category': 'Generic Modules/Sale',
    'summary': 'Product configuration interface modules for Sale',
    'author': 'Business Software Development Solutions',
    'license': 'AGPL-3',
    'website': 'businesssoftwaredevelopmentsolutions.com',
    'depends': ['sale_management', 'product_configurator'],
    'data': ['data/menu_product.xml', 'views/sale_view.xml'],
    'demo': ['demo/res_partner_demo.xml'],
    'images': [],
    'test': [],
    'installable': True,
    'auto_install': True,
}
